"""Add str method in charity project model

Revision ID: 568ca4a4c3b1
Revises: 313585e0a6a1
Create Date: 2025-03-16 13:15:14.813902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568ca4a4c3b1'
down_revision = '313585e0a6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
